// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: coba.proto

package pbuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP status of the response
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// message of the response
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	mi := &file_coba_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_coba_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_coba_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseHeader) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ResponseHeader) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HelloRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name you want to greet
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_coba_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coba_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_coba_proto_rawDescGZIP(), []int{1}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloRequestMultiple struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// multiple names you want to greet
	Name          []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequestMultiple) Reset() {
	*x = HelloRequestMultiple{}
	mi := &file_coba_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequestMultiple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequestMultiple) ProtoMessage() {}

func (x *HelloRequestMultiple) ProtoReflect() protoreflect.Message {
	mi := &file_coba_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequestMultiple.ProtoReflect.Descriptor instead.
func (*HelloRequestMultiple) Descriptor() ([]byte, []int) {
	return file_coba_proto_rawDescGZIP(), []int{2}
}

func (x *HelloRequestMultiple) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

type HelloResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// response header
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// message you get
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_coba_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coba_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_coba_proto_rawDescGZIP(), []int{3}
}

func (x *HelloResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_coba_proto protoreflect.FileDescriptor

const file_coba_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"coba.proto\x12\x04pbuf\"B\n" +
	"\x0eResponseHeader\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"*\n" +
	"\x14HelloRequestMultiple\x12\x12\n" +
	"\x04name\x18\x01 \x03(\tR\x04name\"W\n" +
	"\rHelloResponse\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.pbuf.ResponseHeaderR\x06header\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc3\x01\n" +
	"\aGreeter\x125\n" +
	"\bSayHello\x12\x12.pbuf.HelloRequest\x1a\x13.pbuf.HelloResponse\"\x00\x12E\n" +
	"\x10SayHelloMultiple\x12\x1a.pbuf.HelloRequestMultiple\x1a\x13.pbuf.HelloResponse\"\x00\x12:\n" +
	"\rSayHelloError\x12\x12.pbuf.HelloRequest\x1a\x13.pbuf.HelloResponse\"\x00B\x0fZ\rfrascati/pbufb\x06proto3"

var (
	file_coba_proto_rawDescOnce sync.Once
	file_coba_proto_rawDescData []byte
)

func file_coba_proto_rawDescGZIP() []byte {
	file_coba_proto_rawDescOnce.Do(func() {
		file_coba_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coba_proto_rawDesc), len(file_coba_proto_rawDesc)))
	})
	return file_coba_proto_rawDescData
}

var file_coba_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_coba_proto_goTypes = []any{
	(*ResponseHeader)(nil),       // 0: pbuf.ResponseHeader
	(*HelloRequest)(nil),         // 1: pbuf.HelloRequest
	(*HelloRequestMultiple)(nil), // 2: pbuf.HelloRequestMultiple
	(*HelloResponse)(nil),        // 3: pbuf.HelloResponse
}
var file_coba_proto_depIdxs = []int32{
	0, // 0: pbuf.HelloResponse.header:type_name -> pbuf.ResponseHeader
	1, // 1: pbuf.Greeter.SayHello:input_type -> pbuf.HelloRequest
	2, // 2: pbuf.Greeter.SayHelloMultiple:input_type -> pbuf.HelloRequestMultiple
	1, // 3: pbuf.Greeter.SayHelloError:input_type -> pbuf.HelloRequest
	3, // 4: pbuf.Greeter.SayHello:output_type -> pbuf.HelloResponse
	3, // 5: pbuf.Greeter.SayHelloMultiple:output_type -> pbuf.HelloResponse
	3, // 6: pbuf.Greeter.SayHelloError:output_type -> pbuf.HelloResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coba_proto_init() }
func file_coba_proto_init() {
	if File_coba_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coba_proto_rawDesc), len(file_coba_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coba_proto_goTypes,
		DependencyIndexes: file_coba_proto_depIdxs,
		MessageInfos:      file_coba_proto_msgTypes,
	}.Build()
	File_coba_proto = out.File
	file_coba_proto_goTypes = nil
	file_coba_proto_depIdxs = nil
}
