FROM node:24.14.0 AS builder

# ENV NODE_ENV production

WORKDIR /frontend

COPY ./package.json ./package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.27.3-bookworm-perl

EXPOSE 3000

COPY --from=builder /frontend/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

