# stage 1: builder
FROM node:24.14.0 AS builder

WORKDIR /frontend

COPY ./package.json ./package-lock.json ./
RUN npm ci

COPY . .

RUN npm run build
RUN npm prune --omit=dev

# stage 2 deploy
FROM node:24.14.0

WORKDIR /app

COPY --from=builder /frontend/package.json /app/package.json
COPY --from=builder /frontend/node_modules /app/node_modules
COPY --from=builder /frontend/build /app/build
COPY --from=builder /frontend/.env.empty /app/.env 

ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", "-r", "dotenv/config", "build"]