-- This file (initdb.sql) is generated
-- DO NOT edit this file directly
-- Always run sqlmerger when there's any change in any .sql file in this directory
-- so that the changes in those files reflected to this file (initdb.sql)

-- for docker
SELECT 'CREATE DATABASE regulatedb'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'regulatedb')
\gexec
;