-- This file (initdb.sql) is generated
-- DO NOT edit this file directly
-- Always run sqlmerger when there's any change in any .sql file in this directory
-- so that the changes in those files reflected to this file (initdb.sql)

-- for docker
SELECT 'CREATE DATABASE regulatedb'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'regulatedb')
\gexec
;

CREATE TABLE IF NOT EXISTS users(
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    email VARCHAR UNIQUE,
    username VARCHAR UNIQUE NOT NULL,
    password VARCHAR,
    display_name VARCHAR NOT NULL,
    user_role SMALLINT NOT NULL,
    civitas_id VARCHAR UNIQUE,
    has_sso_login BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS courses(
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    name VARCHAR(100) NOT NULL,
    course_year SMALLINT NOT NULL,
    semester SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS course_members(
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    course_id BIGINT NOT NULL REFERENCES courses(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    course_role SMALLINT NOT NULL
);

